# Generated by Django 5.2.11 on 2026-02-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingagency',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='customsagent',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='historicalbookingagency',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='historicalcarrier',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='historicalcustomsagent',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='historicalvendor',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='agency',
        ),
    ]
